const QRCode = require('qrcode');
const Visitor = require('../models/Visitor');

// Generate QR Code for Visitor
exports.generateQR = async (req, res) => {
  try {
    const { visitorName, visitorPhone, purpose, expectedDate } = req.body;

    // Generate unique QR code data
    const qrData = `VISITOR-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

    // Generate QR code image
    const qrCodeImage = await QRCode.toDataURL(qrData);

    const visitor = await Visitor.create({
      userId: req.user.id,
      qrCode: qrData,
      visitorName,
      visitorPhone,
      purpose: purpose || 'General Visit',
      expectedDate: expectedDate || new Date(),
      verified: false,
      residentId: req.user.id
    });

    res.status(201).json({
      visitor,
      qrCodeImage
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Verify and Check-in Visitor
exports.verifyVisitor = async (req, res) => {
  try {
    const { qrCode } = req.body;

    if (!qrCode || !qrCode.startsWith('VISITOR-')) {
      return res.status(400).json({ message: 'Invalid QR code format. Must start with VISITOR-' });
    }

    const visitor = await Visitor.findOne({ qrCode })
      .populate('residentId', 'fullName block houseNumber phone');

    if (!visitor) {
      return res.status(404).json({ message: 'QR code not found in system. This QR was not generated by any resident.' });
    }

    if (visitor.entryTime) {
      return res.status(400).json({ message: `Visitor already checked in at ${new Date(visitor.entryTime).toLocaleString()}` });
    }

    visitor.entryTime = new Date();
    visitor.verified = true;
    visitor.verifiedBy = req.user.fullName || 'Security';
    await visitor.save();

    res.json({
      visitorName: visitor.visitorName,
      visitorPhone: visitor.visitorPhone,
      purpose: visitor.purpose,
      residentName: visitor.residentId?.fullName,
      block: visitor.residentId?.block,
      houseNumber: visitor.residentId?.houseNumber,
      entryTime: visitor.entryTime
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get User Visitors
exports.getUserVisitors = async (req, res) => {
  try {
    const visitors = await Visitor.find({ residentId: req.user.id })
      .sort('-createdAt');
    res.json(visitors);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get All Pending Visitors (Security)
exports.getAllPendingVisitors = async (req, res) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    const visitors = await Visitor.find({
      expectedDate: { $gte: today, $lt: tomorrow },
      verified: false
    })
      .populate('residentId', 'fullName block houseNumber phone')
      .sort('expectedDate');
    
    res.json(visitors);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Check-in Visitor by ID (Security)
exports.checkInVisitor = async (req, res) => {
  try {
    const visitor = await Visitor.findById(req.params.id)
      .populate('residentId', 'fullName block houseNumber');

    if (!visitor) {
      return res.status(404).json({ message: 'Visitor not found' });
    }

    if (visitor.entryTime) {
      return res.status(400).json({ message: 'Visitor already checked in' });
    }

    visitor.entryTime = new Date();
    visitor.verified = true;
    visitor.verifiedBy = req.user.fullName || 'Security';
    await visitor.save();

    res.json({ message: 'Visitor checked in successfully', visitor });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
